version: 3
tasks:
  gql.export:
    cmds:
      - cargo run -- --export
    silent: false
  sql.export:
    cmds:
      - pg_dump -U postgres -p 5432 -h localhost main_dev > docs/database.sql --schema-only --no-owner --no-comments --no-privileges
    env:
      PGPASSWORD: postgres
    silent: false
