[env]
# Configure the tracing
RUST_LOG = "rpg=debug,tower_http=debug,axum::rejection=trace"
# Configure the database
DATABASE_URL = "postgres://postgres:postgres@localhost:5432/main_dev?sslmode=disable"
# Configure the endpoint
ENDPOINT_URL = "0.0.0.0:4000"
